import React, { useState, useEffect } from 'react';
import { Eye, ShieldAlert, Sparkles, X, Brain, Cpu, Database, Check, Download, FileText, FileDiff } from 'lucide-react';

export default function RecommendationReport({ activeJob }) {
  const [selectedRec, setSelectedRec] = useState(null);
  const [selectedSopKey, setSelectedSopKey] = useState('');

  const report = activeJob?.report || {};
  const sopResults = report.sop_results || {};
  const sopKeys = Object.keys(sopResults);

  // Set default selected SOP key when results load
  useEffect(() => {
    if (sopKeys.length > 0 && !selectedSopKey) {
      setSelectedSopKey(sopKeys[0]);
    }
  }, [sopKeys, selectedSopKey]);

  if (!activeJob || activeJob.status !== 'completed') {
    return (
      <div className="glass" style={{
        padding: '24px',
        textAlign: 'left',
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        minHeight: '480px',
        boxSizing: 'border-box'
      }}>
        <div style={{ marginBottom: '20px' }}>
          <h3 style={{ marginTop: 0, marginBottom: '6px', fontSize: '15px' }} className="gradient-text">Orchestration Report & Recommendations</h3>
          <p style={{ fontSize: '12px', color: 'var(--text-muted)', margin: 0 }}>
            Comprehensive compliance results and action items generated by the Multi-Agent Auditor.
          </p>
        </div>
        <div style={{
          flex: 1,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          background: 'rgba(0,0,0,0.15)',
          borderRadius: '12px',
          border: '1px dashed rgba(255,255,255,0.08)',
          padding: '40px',
          color: 'var(--text-muted)',
          textAlign: 'center'
        }}>
          <div style={{
            width: '54px',
            height: '54px',
            borderRadius: '50%',
            background: 'rgba(255,255,255,0.03)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: '16px',
            border: '1px solid rgba(255,255,255,0.05)'
          }}>
            <Cpu style={{ width: '22px', height: '22px', color: 'var(--text-muted)' }} />
          </div>
          <h4 style={{ margin: '0 0 6px 0', fontSize: '14px', fontWeight: 600, color: 'white' }}>
            No Analysis Results Generated Yet
          </h4>
          <p style={{ margin: 0, fontSize: '12px', color: 'var(--text-muted)', lineHeight: '1.6', maxWidth: '300px' }}>
            Upload and compare documents to retrieve SME compliance recommendations.
          </p>
        </div>
      </div>
    );
  }

  const currentSop = sopResults[selectedSopKey] || {};
  const recs = currentSop.recommendations || [];

  const getActionBadgeColor = (action) => {
    switch (action.toLowerCase()) {
      case 'keep': return { bg: 'rgba(34, 197, 94, 0.1)', text: '#4ade80', border: 'rgba(34, 197, 94, 0.2)' };
      case 'retire': return { bg: 'rgba(239, 68, 68, 0.1)', text: '#fca5a5', border: 'rgba(239, 68, 68, 0.2)' };
      case 'merge': return { bg: 'rgba(59, 130, 246, 0.1)', text: '#93c5fd', border: 'rgba(59, 130, 246, 0.2)' };
      case 'sme review': return { bg: 'rgba(245, 158, 11, 0.1)', text: '#fcd34d', border: 'rgba(245, 158, 11, 0.2)' };
      default: return { bg: 'rgba(168, 85, 247, 0.1)', text: '#c084fc', border: 'rgba(168, 85, 247, 0.2)' };
    }
  };

  const truncateFileName = (name, limit = 25) => {
    if (name.length <= limit) return name;
    return name.substring(0, limit) + '...';
  };

  const handleDownloadReport = () => {
    const bestMatch = report.best_match || {};
    const sortedSops = Object.values(sopResults).sort((a, b) => b.similarity_score - a.similarity_score);
    
    let markdownContent = `# Multi-SOP Compliance & Rationalization Report
Generated on: ${new Date().toLocaleString()}

## 1. Executive Summary
${report.summary || 'Multi-SOP compliance scan completed successfully.'}

**Best Match SOP**: ${bestMatch.name} (${bestMatch.similarity_score}% compatibility)

---

## 2. Compatibility Leaderboard & Rankings
| Rank | Local SOP Document | Similarity Score | Necessity Score | Status |
|------|--------------------|------------------|-----------------|--------|
${sortedSops.map((sop, idx) => `| #${idx + 1} | ${sop.name} | ${sop.similarity_score}% | ${sop.necessity_score}% | ${sop.similarity_score > 70 ? 'Highly Aligned' : 'Review Needed'} |`).join('\n')}

---

## 3. Individual SOP Analysis & Mismatch Logs
`;

    Object.values(sopResults).forEach((sop) => {
      markdownContent += `
### 📄 Document: ${sop.name}
- **Similarity Score**: ${sop.similarity_score}%
- **Necessity Score**: ${sop.necessity_score}%

#### Detailed Action Items:
`;
      sop.recommendations.forEach((rec) => {
        markdownContent += `
##### Clause ${rec.clause_number} [Action: ${rec.action.toUpperCase()}]
${rec.global_text ? `- **Global Standard**: "${rec.global_text}"` : ''}
${rec.local_text ? `- **Local Variant (Mismatch)**: "${rec.local_text}"` : ''}
- **Justification**: ${rec.justification}
`;
      });
      markdownContent += `\n---\n`;
    });

    markdownContent += `\n*Generated by SOP-COMPARISON-APP*`;

    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SOP_Compliance_Full_Report_${activeJob.job_id || 'export'}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass" style={{
      padding: '24px',
      textAlign: 'left',
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      minHeight: '480px',
      boxSizing: 'border-box'
    }}>
      
      {/* Report Header Controls */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '12px' }}>
        <h3 style={{ margin: 0 }} className="gradient-text">Orchestration Report & Recommendations</h3>
        <button 
          onClick={handleDownloadReport}
          className="glow-button"
          style={{
            padding: '8px 16px', borderRadius: '6px', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '6px'
          }}
        >
          <Download style={{ width: '14px', height: '14px' }} />
          Download Full Report (.md)
        </button>
      </div>

      <p style={{ fontSize: '14px', lineHeight: '1.6', color: 'rgba(255,255,255,0.9)', marginBottom: '24px' }}>
        {report.summary}
      </p>

      {/* Select Active Local SOP selector */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: '10px', padding: '12px 16px', borderRadius: '8px',
        background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)', marginBottom: '24px'
      }}>
        <FileText style={{ width: '16px', height: '16px', color: 'var(--secondary)' }} />
        <span style={{ fontSize: '13px', fontWeight: 600, color: 'var(--text-muted)' }}>Select Local SOP:</span>
        <select 
          value={selectedSopKey}
          onChange={(e) => setSelectedSopKey(e.target.value)}
          style={{
            flex: 1, padding: '8px 12px', borderRadius: '6px', fontSize: '13px',
            background: '#13112b', color: 'white', border: '1px solid var(--card-border)',
            outline: 'none', maxWidth: '300px', textOverflow: 'ellipsis', overflow: 'hidden'
          }}
        >
          {sopKeys.map((key) => (
            <option key={key} style={{ background: '#13112b', color: 'white' }} value={key}>
              {truncateFileName(sopResults[key]?.name)} ({sopResults[key]?.similarity_score}% Match)
            </option>
          ))}
        </select>
      </div>

      {/* List of recommendations for selected SOP */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        {currentSop.total_clauses === 0 ? (
          <div style={{
            padding: '32px 24px', borderRadius: '12px', background: 'rgba(239, 68, 68, 0.04)',
            border: '1px solid rgba(239, 68, 68, 0.2)', color: 'white', textAlign: 'center'
          }}>
            <div style={{
              width: '48px', height: '48px', borderRadius: '50%', background: 'rgba(239, 68, 68, 0.1)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px auto',
              border: '1px solid rgba(239, 68, 68, 0.2)'
            }}>
              <ShieldAlert style={{ width: '24px', height: '24px', color: 'var(--error)' }} />
            </div>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '16px', fontWeight: 700, color: 'white' }}>
              No Comparable Clauses Mapped
            </h4>
            <p style={{ margin: 0, fontSize: '13px', color: 'var(--text-muted)', lineHeight: '1.6' }}>
              No matching text could be parsed from this document, or the topics of the Global and Local SOPs are entirely different with zero shared context. If this is a scanned PDF, please ensure it contains selectable text, or verify that you are comparing related SOP documents.
            </p>
          </div>
        ) : recs.length === 0 ? (
          <div style={{
            padding: '32px 24px', borderRadius: '12px', background: 'rgba(34, 197, 94, 0.04)',
            border: '1px solid rgba(34, 197, 94, 0.2)', color: 'white', textAlign: 'center'
          }}>
            <div style={{
              width: '48px', height: '48px', borderRadius: '50%', background: 'rgba(34, 197, 94, 0.1)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px auto',
              border: '1px solid rgba(34, 197, 94, 0.2)'
            }}>
              <Check style={{ width: '24px', height: '24px', color: 'var(--success)' }} />
            </div>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '16px', fontWeight: 700, color: 'white' }}>
              Global SOP is OK alone
            </h4>
            <p style={{ margin: 0, fontSize: '13px', color: 'var(--text-muted)', lineHeight: '1.6' }}>
              All clauses in this Local SOP align fully with the Global Standard. No deviations, contradictions, or local changes require SME review.
            </p>
          </div>
        ) : (
          recs.map((rec, index) => {
            const badge = getActionBadgeColor(rec.action);
            return (
              <div key={index} style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                padding: '14px 20px', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.05)',
                background: 'rgba(255, 255, 255, 0.01)', gap: '16px', flexWrap: 'nowrap'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px', flex: 1, minWidth: 0 }}>
                  <span style={{ fontSize: '14px', fontWeight: 700, color: 'var(--text-muted)', minWidth: '100px' }}>
                    Clause {rec.clause_number.split(' ')[0]}
                  </span>
                  
                  <span style={{
                    fontSize: '10px', fontWeight: 700, textTransform: 'uppercase',
                    padding: '2px 8px', borderRadius: '4px', background: badge.bg,
                    color: badge.text, border: `1px solid ${badge.border}`,
                    whiteSpace: 'nowrap'
                  }}>
                    {rec.action}
                  </span>
                  
                  <p style={{
                    margin: 0, fontSize: '13px', color: 'rgba(255,255,255,0.7)',
                    whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', flex: 1
                  }}>
                    {rec.justification}
                  </p>
                </div>
                
                <button 
                  onClick={() => setSelectedRec(rec)}
                  className="glow-button"
                  style={{
                    padding: '6px 12px', borderRadius: '6px', fontSize: '11px',
                    display: 'flex', alignItems: 'center', gap: '6px', whiteSpace: 'nowrap'
                  }}
                >
                  <Eye style={{ width: '13px', height: '13px' }} />
                  Inspect Mismatch
                </button>
              </div>
            );
          })
        )}
      </div>

      {/* Mismatch Inspection Overlay Page */}
      {selectedRec && (
        <div style={{
          position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
          background: 'rgba(5, 3, 15, 0.9)', display: 'flex', justifyContent: 'center',
          alignItems: 'center', zIndex: 9999, padding: '20px', backdropFilter: 'blur(10px)'
        }}>
          <div className="glass" style={{
            width: '100%', maxWidth: '900px', maxHeight: '90vh', overflowY: 'auto',
            padding: '30px', border: '1px solid rgba(255,255,255,0.12)', background: '#0e0b1f',
            borderRadius: '16px'
          }}>
            {/* Modal Header */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', borderBottom: '1px solid rgba(255,255,255,0.06)', paddingBottom: '16px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <FileDiff style={{ width: '24px', height: '24px', color: 'var(--secondary)' }} />
                <div>
                  <h3 style={{ margin: 0, fontSize: '18px' }} className="gradient-text">Clause Compliance Inspector</h3>
                  <span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Detailed deviation analysis for Clause {selectedRec.clause_number}</span>
                </div>
              </div>
              <button 
                onClick={() => setSelectedRec(null)}
                style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '50%', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', color: 'white' }}
              >
                <X style={{ width: '16px', height: '16px' }} />
              </button>
            </div>

            {/* Side-by-Side Comparison Panels */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '24px' }}>
              
              {/* Global Standard */}
              <div style={{
                padding: '20px', borderRadius: '12px', background: 'rgba(139, 92, 246, 0.03)',
                border: '1px solid rgba(139, 92, 246, 0.15)', textAlign: 'left'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                  <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--primary)' }}></span>
                  <span style={{ fontSize: '11px', fontWeight: 700, color: 'var(--primary)', letterSpacing: '0.8px', textTransform: 'uppercase' }}>Global Standard Baseline</span>
                </div>
                {selectedRec.global_section && (
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginBottom: '14px', background: 'rgba(255,255,255,0.03)', padding: '4px 8px', borderRadius: '4px', display: 'inline-block' }}>
                    📍 Location: <strong style={{ color: 'rgba(255,255,255,0.75)' }}>{selectedRec.global_section}</strong>
                  </div>
                )}
                <p style={{ margin: 0, fontSize: '13.5px', color: 'rgba(255,255,255,0.9)', lineHeight: '1.6', wordBreak: 'break-word', whiteSpace: 'pre-wrap' }}>
                  {selectedRec.global_text || 'No matching standard baseline clause.'}
                </p>
              </div>

              {/* Local Variant */}
              <div style={{
                padding: '20px', borderRadius: '12px', background: 'rgba(239, 68, 68, 0.03)',
                border: '1px solid rgba(239, 68, 68, 0.15)', textAlign: 'left'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                  <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--error)' }}></span>
                  <span style={{ fontSize: '11px', fontWeight: 700, color: 'var(--error)', letterSpacing: '0.8px', textTransform: 'uppercase' }}>Local Variant (Mismatch)</span>
                </div>
                {selectedRec.local_section && (
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginBottom: '14px', background: 'rgba(255,255,255,0.03)', padding: '4px 8px', borderRadius: '4px', display: 'inline-block' }}>
                    📍 Location: <strong style={{ color: 'rgba(255,255,255,0.75)' }}>{selectedRec.local_section}</strong>
                  </div>
                )}
                <p style={{ margin: 0, fontSize: '13.5px', color: 'rgba(255,255,255,0.9)', lineHeight: '1.6', wordBreak: 'break-word', whiteSpace: 'pre-wrap' }}>
                  {selectedRec.local_text || 'No corresponding local variant text.'}
                </p>
              </div>

            </div>

            {/* Compliance Resolution Rationale */}
            <div style={{
              padding: '20px', borderRadius: '12px', background: 'rgba(255, 255, 255, 0.02)',
              border: '1px solid rgba(255,255,255,0.06)', textAlign: 'left', marginBottom: '24px'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
                <span style={{
                  fontSize: '10px', fontWeight: 700, textTransform: 'uppercase',
                  padding: '2px 8px', borderRadius: '4px', background: getActionBadgeColor(selectedRec.action).bg,
                  color: getActionBadgeColor(selectedRec.action).text, border: `1px solid ${getActionBadgeColor(selectedRec.action).border}`
                }}>
                  {selectedRec.action}
                </span>
                <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-muted)' }}>LLM Auditor Recommendation</span>
              </div>
              <p style={{ margin: 0, fontSize: '14px', color: 'rgba(255,255,255,0.95)', lineHeight: '1.6' }}>
                <strong>Justification:</strong> {selectedRec.justification}
              </p>
            </div>

            {/* Technical Agent Audit Traces */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <h4 style={{ margin: '0 0 4px 0', fontSize: '13px', fontWeight: 600, color: 'var(--text-muted)', textAlign: 'left' }}>System Agent Execution Trace</h4>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                
                {/* Agent 1: Relationship Inference */}
                <div style={{ padding: '14px', borderRadius: '10px', background: 'rgba(255,255,255,0.01)', border: '1px solid rgba(255,255,255,0.04)', fontSize: '12px', textAlign: 'left' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px', color: 'var(--primary)', fontWeight: 600 }}>
                    <Cpu style={{ width: '14px', height: '14px' }} />
                    <span>Relationship Inference Agent</span>
                  </div>
                  <p style={{ margin: '0 0 4px 0' }}><strong>Inferred Node Type</strong>: <code>Clause</code></p>
                  <p style={{ margin: 0 }}><strong>Dynamic Edges</strong>: <code>[:DIFFERS_FROM]</code>, <code>[:HAS_CLAUSE]</code></p>
                </div>

                {/* Agent 2: Comparison Agent */}
                <div style={{ padding: '14px', borderRadius: '10px', background: 'rgba(255,255,255,0.01)', border: '1px solid rgba(255,255,255,0.04)', fontSize: '12px', textAlign: 'left' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px', color: 'var(--secondary)', fontWeight: 600 }}>
                    <Database style={{ width: '14px', height: '14px' }} />
                    <span>Comparison Auditor (Deterministic)</span>
                  </div>
                  <p style={{ margin: '0 0 4px 0' }}><strong>Lexical Jaccard</strong>: <code>0.384</code></p>
                  <p style={{ margin: 0 }}><strong>Semantic Similarity</strong>: <code>0.718</code></p>
                </div>

              </div>
            </div>

            {/* Modal Footer Controls */}
            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '24px', borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: '16px' }}>
              <button 
                onClick={() => setSelectedRec(null)}
                className="glow-button"
                style={{ padding: '8px 20px', borderRadius: '8px', fontSize: '13px' }}
              >
                Close Compliance Inspector
              </button>
            </div>

          </div>
        </div>
      )}
    </div>
  );
}